"""Render training/data/DATACARD.md from the build report, so every number in it comes from the build."""

from training.data.rows import SYNTHETIC_KINDS
from training.labels import LABELS

LIMITATIONS = (
    "OpenCC conversions do not read like natively written Simplified or Traditional Chinese.",
    "Crops of 1-3 words are cut from sentences, not collected from real queries.",
    "Code-mixed rows are two whole sentences joined and labelled with the longer part; "
    "real code-mixing happens inside sentences.",
    "The contamination check matches whole lines after normalization. A FLORES-200 sentence "
    "embedded inside a longer OpenLID line is not caught.",
    'Where a split is marked "no" under source-disjoint, it was carved from the same sources as '
    "training, so its scores are likely higher than on text from new sources.",
    "Romanized Hindi and Urdu come from one source (Dakshina: Wikipedia sentences romanized by "
    "annotators), so they are split by hash and are not source-disjoint.",
)


def _synthetic_total(cell: dict) -> int:
    return sum(cell.get(kind, 0) for kind in SYNTHETIC_KINDS)


def render_card(report: dict) -> str:
    config = report["config"]
    sources = report["sources"]
    openlid, dakshina, flores = sources["openlid"], sources["dakshina"], sources["flores"]
    counts = report["counts"]
    lines = [
        "# Language-ID training data card",
        "",
        f"Generated by `training/data/build.py` on {report['built_at'][:10]} with seed {config['seed']}. "
        "The data is not in this repository; this card and the matching `results/lid-data-*.json` "
        "record how it was built.",
        "",
        "## Sources",
        "",
        "| Source | Version | Licence | Used for |",
        "|---|---|---|---|",
        f"| [OpenLID]({openlid['url']}) | revision `{openlid['revision'][:12]}`, "
        f"{len(openlid['shards_used'])} of {openlid['shards_available']} shards | {openlid['licence']} | "
        "natural lines for 9 labels and `other` |",
        f"| [Dakshina v1.0]({dakshina['url']}) | SHA-256 `{dakshina['archive_sha256'][:16]}...` | "
        f"{dakshina['licence']} | romanized Hindi and Urdu: dev sentences, train and dev lexicons "
        "(test files held out) |",
        f"| [FLORES-200]({flores['url']}) | SHA-256 `{flores['sha256'][:16]}...` | {flores['licence']} | "
        "contamination check only (dev and devtest) |",
        "",
        "## Sampling and cleaning",
        "",
        f"- OpenLID: up to {config['target_cap']:,} lines per label and {config['other_cap']:,} per other "
        f"language, shards read in seeded order, stopping when every label reached its cap or after "
        f"{config['max_shards']} shards.",
    ]
    short = report["openlid_below_cap"]
    lines.append(
        "- Every label reached its cap."
        if not short
        else "- Labels below the cap: "
        + ", ".join(f"`{label}` ({n:,})" for label, n in sorted(short.items()))
        + "."
    )
    cleaning = report["cleaning"]
    lines += [
        "- Cleaning uses the app's normalization (NFKC, invisible characters removed, whitespace collapsed), "
        f"drops lines under 2 characters ({sum(cleaning['too_short'].values()):,} dropped) and exact "
        f"duplicates ({sum(cleaning['duplicates'].values()):,} dropped).",
        f"- Contamination: {sum(cleaning['contaminated'].values()):,} lines removed because they match "
        f"a FLORES-200 dev or devtest sentence ({report['held_out']['flores_sentences']:,} checked) or a "
        f"Dakshina test sentence or word ({report['held_out']['dakshina_test_lines']:,} checked).",
        f"- Synthetic rows: OpenCC conversions (up to {config['opencc_per_label']:,} per Chinese label), "
        f"crops of 1-3 words from {config['crop_fraction']:.0%} of natural lines, and code-mixed rows "
        f"equal to {config['code_mixed_fraction']:.0%} of natural lines.",
        f"- `val_select` holds up to {config['select_per_label']:,} validation rows per label; every model "
        "is chosen on it.",
        "",
        "## Rows per split",
        "",
        "| Label | train natural | train synthetic | val natural | val synthetic "
        "| test natural | test synthetic |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for label in LABELS:
        cells = []
        for split in ("train", "val", "test"):
            cell = counts[split].get(label, {})
            cells += [f"{cell.get('natural', 0):,}", f"{_synthetic_total(cell):,}"]
        lines.append(f"| `{label}` | " + " | ".join(cells) + " |")
    lines += [
        "",
        "## Split separation",
        "",
        "| Label | test sources | validation sources | test source-disjoint | validation source-disjoint |",
        "|---|---|---|---|---|",
    ]
    for label, plan in sorted(report["split_plans"].items()):
        by_split = {
            name: sorted(s for s, split in plan["sources"].items() if split == name)
            for name in ("val", "test")
        }
        lines.append(
            f"| `{label}` | {', '.join(by_split['test']) or '(hash split)'} | "
            f"{', '.join(by_split['val']) or '(hash split)'} | "
            f"{'yes' if plan['test_source_disjoint'] else 'no'} | "
            f"{'yes' if plan['val_source_disjoint'] else 'no'} |"
        )
    lines += ["", "## Limitations", ""] + [f"- {item}" for item in LIMITATIONS] + [""]
    return "\n".join(lines)
